'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { spawn } = require('node:child_process');
const { once } = require('node:events');
const { createMessageConnection, StreamMessageReader, StreamMessageWriter } = require('vscode-jsonrpc/node');
const { URI } = require('vscode-uri');
test('bundled server speaks stdio LSP: initialize, edits, completion, navigation, watchers, close and shutdown', { timeout: 15000 }, async t => {
  const root = path.resolve(__dirname, '../.test-work/protocol/content');
  const targetFile = path.join(root, 'posts/目标/index.md');
  fs.mkdirSync(path.dirname(targetFile), { recursive: true });
  fs.writeFileSync(targetFile, '+++\ntitle = "协议目标"\n+++\n## 章节\n');
  const uri = URI.file(path.join(root, 'posts/来源/index.md')).toString();
  const targetUri = URI.file(targetFile).toString();
  const child = spawn(process.execPath, [path.resolve(__dirname, '../dist/server.cjs'), '--stdio'], { stdio: ['pipe', 'pipe', 'pipe'], windowsHide: true });
  let stderr = ''; child.stderr.on('data', chunk => { stderr += chunk; });
  const rpc = createMessageConnection(new StreamMessageReader(child.stdout), new StreamMessageWriter(child.stdin));
  t.after(() => { rpc.dispose(); child.kill(); });
  const diagnostics = new Map();
  rpc.onNotification('textDocument/publishDiagnostics', p => diagnostics.set(p.uri, p));
  rpc.listen();
  const init = await rpc.sendRequest('initialize', { processId: process.pid, rootUri: URI.file(root).toString(), capabilities: {}, initializationOptions: { contentRoot: root } });
  assert.equal(init.capabilities.textDocumentSync, 2);
  await rpc.sendNotification('initialized', {});
  const text = '+++\ntitle = "来源"\n+++\n[[协议目标#章节]]\n[[协议';
  await rpc.sendNotification('textDocument/didOpen', { textDocument: { uri, version: 1, languageId: 'markdown', text } });
  const completions = await rpc.sendRequest('textDocument/completion', { textDocument: { uri }, position: { line: 4, character: 4 } });
  assert(completions.some(item => item.label === '协议目标'));
  const def = await rpc.sendRequest('textDocument/definition', { textDocument: { uri }, position: { line: 3, character: 4 } });
  assert.equal(def.uri, targetUri); assert.equal(def.range.start.line, 3);
  const hover = await rpc.sendRequest('textDocument/hover', { textDocument: { uri }, position: { line: 3, character: 4 } });
  assert.match(hover.contents.value, /协议目标/);
  const refs = await rpc.sendRequest('textDocument/references', { textDocument: { uri: targetUri }, position: { line: 1, character: 2 }, context: { includeDeclaration: true } });
  assert.equal(refs.length, 2);
  await rpc.sendNotification('textDocument/didChange', { textDocument: { uri, version: 2 }, contentChanges: [{ range: { start: { line: 3, character: 2 }, end: { line: 3, character: 6 } }, text: '失效' }] });
  const waitFor = async predicate => { const until = Date.now() + 3000; while (!predicate() && Date.now() < until) await new Promise(r => setTimeout(r, 25)); assert(predicate(), stderr); };
  await waitFor(() => diagnostics.get(uri)?.version === 2 && diagnostics.get(uri)?.diagnostics.some(d => d.code === 'link-missing'));
  fs.unlinkSync(targetFile);
  await rpc.sendNotification('workspace/didChangeWatchedFiles', { changes: [{ uri: targetUri, type: 3 }] });
  await waitFor(() => diagnostics.get(targetUri)?.diagnostics.length === 0);
  await rpc.sendNotification('textDocument/didClose', { textDocument: { uri } });
  await waitFor(() => diagnostics.get(uri)?.diagnostics.length === 0);
  await rpc.sendRequest('shutdown'); await rpc.sendNotification('exit');
  const [code] = await once(child, 'exit'); assert.equal(code, 0, stderr);
});
